DROP TABLE IF EXISTS staging.app_details;

CREATE TABLE IF NOT EXISTS staging.app_details (
	appid INTEGER PRIMARY KEY,
    name VARCHAR(255),
    game_appid INTEGER,
    enrich_is_description BOOLEAN,
    long_description TEXT,
    short_description TEXT,
    image_header TEXT,
    image_background TEXT,
    image_screenshots TEXT,
    image_movies TEXT,
    enrich_is_price BOOLEAN,
    is_free BOOLEAN,
    currency CHAR(3),
    price NUMERIC(10, 2),
    type app_type,
    categories TEXT [],
    genres TEXT [],
    supported_languages TEXT,
    controller_support BOOLEAN,
    enrich_is_date BOOLEAN,
    release_date DATE,
    required_age SMALLINT,
    developers TEXT [],
    publishers TEXT [],
    content_descriptors_notes TEXT,
    achievements JSONB,
    enrich_is_windows BOOLEAN,
    is_windows BOOLEAN,
    windows_requirements_minimum TEXT,
    windows_requirements_recommended TEXT,
    enrich_is_mac BOOLEAN,
    is_mac BOOLEAN,
    mac_requirements_minimum TEXT,
    mac_requirements_recommended TEXT,
    enrich_is_linux BOOLEAN,
    is_linux BOOLEAN,
    linux_requirements_minimum TEXT,
    linux_requirements_recommended TEXT
);